/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */

export interface CatchOptions {
    ErrorEquals: [string, ...string[]]
    Next: string
    ResultPath?: string
}

export interface RetryOptions {
    ErrorEquals: [string, ...string[]]
    IntervalSeconds?: number
    MaxAttempts?: number
    BackoffRate?: number
}
