/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface RetryOptions {
    ErrorEquals: [string, ...string[]]
    IntervalSeconds?: number
    MaxAttempts?: number
    BackoffRate?: number
}
