/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export type Choices = {
    [k: string]: unknown
} & {
    Next: string
}

export interface ChoiceState {
    Comment?: string | undefined
    InputPath?: string | undefined
    OutputPath?: string | undefined
    Type: 'Choice'
    Choices: [Choices, ...Choices[]]
    Default?: string | undefined
}
